### ISSUE TITLE
I don't agree your animation of RNN

### ISSUE THREAD

**Issue by chengmingbo** [hkhojasteh/Char-RNN-OpenCV#1]
I believe that there is only one hidden layer when refer to char-rnn.  Instead of 100 hidden layers, I think 'hidden_size=100' is the dimensions of hidden layers. The following animation defines a char-rnn, hidden_size of which is 3:

                     +--------+     +--------+     +--------+    +--------+
                     |   0.3  |     |   0.6  |     |  0.0   |    |  0.1   |
       output layer  |   0.5  |     |   0.1  |     |  0.5   |    |  0.5   |
                     |   0.1  |     |   0.1  |     |  0.1   |    |  0.3   |
                     |   0.1  |     |   0.2  |     |  0.4   |    |  0.1   |
                     +--------+     +--------+     +--------+    +--------+
                         ^              ^              ^              ^
                         | W_hy         | W_hy         | W_hy         | W_hy
                     +-------+      +-------+      +-------+      +-------+
                     |  0.3  |      |  0.2  |      |  0.1  |      |  0.2  |
                     |  0.2  | W_hh |  0.7  | W_hh |  0.1  | W_hh |  0.6  |
       hidden layer  |  0.5  +----->|  0.1  +----->|  0.8  +----->|  0.2  |
                     +-------+      +-------+      +-------+      +-------+
                          ^              ^              ^             ^
                          | W_xh         | W_xh         | W_xh        | W_xh
                     +-------+      +-------+      +-------+      +-------+
                     |   1   |      |   0   |      |   0   |      |   0   |
        input layer  |   0   |      |   1   |      |   0   |      |   0   |
                     |   0   |      |   0   |      |   1   |      |   0   |
                     |   0   |      |   0   |      |   0   |      |   1   |
                     +-------+      +-------+      +-------+      +-------+

**Comment by hkhojasteh** [comment]
I’d appreciate it.
yep, that's definitely true. I will correct it.
